import type { Decision, Preset, TemplateId } from "../domain/types";
import { templates } from "../domain/templates";

export function Home(props: { decisions: Decision[]; presets: Preset[]; showTemplates: boolean; setShowTemplates: (value: boolean) => void; onCreate: (id: TemplateId) => void; onUsePreset: (preset: Preset) => void; onOpen: (id: string) => void; onDelete: (id: string) => void; onDeletePreset: (id: string) => void; onExport: () => void; onImport: (event: React.ChangeEvent<HTMLInputElement>) => void; }) {
  return <div className="app-shell"><header className="topbar"><div className="brand-mark">DJ</div><div><div className="brand-name">DecisionJudge</div><div className="brand-subtitle">把取舍变成可解释的选择</div></div><div className="topbar-spacer" /><div className="data-actions"><button className="header-action" onClick={props.onExport}>导出</button><label className="header-action">导入<input type="file" accept="application/json,.json" onChange={props.onImport} hidden /></label></div><span className="local-pill"><span className="status-dot" />仅保存在本机</span></header>
    <main className="home-main"><section className="intro-band"><div><p className="eyebrow">深度决策工作台 / 低频 · 高重要</p><h1>先看清代价，<br /><em>再选择方向。</em></h1><p className="intro-copy">看清取舍，验证关键假设，让选择、投入与复盘连成一条线。</p><button className="primary-button" onClick={() => props.setShowTemplates(true)}>新建一项决策 <span>→</span></button></div><div className="intro-diagram" aria-label="决策模型示意"><div className="diagram-axis axis-x" /><div className="diagram-axis axis-y" /><div className="diagram-label label-top">长期价值</div><div className="diagram-label label-right">当下成本</div><div className="diagram-point point-a"><span>方案 A</span></div><div className="diagram-point point-b"><span>方案 B</span></div><div className="diagram-point point-c"><span>现状</span></div></div></section>
      {props.showTemplates && <section className="template-section"><div className="section-heading"><div><p className="eyebrow">选择一个起点</p><h2>这次要决定什么？</h2></div><button className="text-button" onClick={() => props.setShowTemplates(false)}>收起</button></div><div className="template-grid">{templates.map((template, index) => <button className="template-card" key={template.id} onClick={() => props.onCreate(template.id)}><span className="template-index">{String(index + 1).padStart(2, "0")}</span><strong>{template.name}</strong><span>{template.description}</span><small>{template.concepts.join(" · ")}</small><span className="card-arrow">↗</span></button>)}</div>{props.presets.length > 0 && <div className="preset-section"><div className="preset-heading"><p className="eyebrow">我的预设</p><span>已保存的决策结构，可重复使用</span></div><div className="preset-list">{props.presets.map((preset) => <div className="preset-row" key={preset.id}><button onClick={() => props.onUsePreset(preset)}><strong>{preset.name}</strong><span>{preset.description || `${preset.criteria.length} 个评价维度 · ${preset.options.length} 个方案`}</span></button><button className="preset-delete" onClick={() => props.onDeletePreset(preset.id)} title={`删除预设 ${preset.name}`}>×</button></div>)}</div></div>}</section>}
      <section className="recent-section"><div className="section-heading"><div><p className="eyebrow">本地记录</p><h2>最近的决策</h2></div><span className="muted-text">{props.decisions.length} 项</span></div>{props.decisions.length === 0 ? <div className="empty-state"><div className="empty-icon">□</div><strong>还没有保存的决策</strong><span>从一个重要问题开始，给直觉一份可以复查的依据。</span></div> : <div className="decision-list">{props.decisions.map((decision) => <div className="decision-row" key={decision.id}><button className="decision-open" onClick={() => props.onOpen(decision.id)}><span className="decision-status">{decision.status === "decided" ? "已做选择" : "草稿"}</span><strong>{decision.title}</strong><span>{decision.templateName} · {new Date(decision.updatedAt).toLocaleDateString("zh-CN")}</span></button><button className="icon-text-button danger" title="删除这项决策" onClick={() => props.onDelete(decision.id)}>删除</button></div>)}</div>}</section>
    </main><footer className="app-footer"><span>DecisionJudge 0.3</span><span>记录保存在本机 · 问答助手按需连接你的模型服务</span><span>MPL-2.0</span></footer></div>;
}

